import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = "https://rajaa7.com";

  return [
    { url: baseUrl, lastModified: new Date(), changeFrequency: "daily", priority: 1 },
    { url: `${baseUrl}/download`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.9 },
    { url: `${baseUrl}/about`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${baseUrl}/features`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/blog`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.7 },
    { url: `${baseUrl}/blog/raja7-game-complete-guide`, lastModified: new Date("2026-07-01"), changeFrequency: "monthly", priority: 0.7 },
    { url: `${baseUrl}/blog/raja7-apk-download-android`, lastModified: new Date("2026-06-28"), changeFrequency: "monthly", priority: 0.7 },
    { url: `${baseUrl}/blog/raja7-game-register-login`, lastModified: new Date("2026-06-25"), changeFrequency: "monthly", priority: 0.7 },
    { url: `${baseUrl}/blog/how-to-install-raja7-on-android`, lastModified: new Date("2026-06-20"), changeFrequency: "monthly", priority: 0.7 },
    { url: `${baseUrl}/blog/raja7-game-tips-and-tricks`, lastModified: new Date("2026-06-15"), changeFrequency: "monthly", priority: 0.7 },
    { url: `${baseUrl}/blog/raja7-vs-other-gaming-platforms`, lastModified: new Date("2026-06-10"), changeFrequency: "monthly", priority: 0.7 },
    { url: `${baseUrl}/blog/raja7-game-rewards-and-bonuses`, lastModified: new Date("2026-06-05"), changeFrequency: "monthly", priority: 0.7 },
    { url: `${baseUrl}/blog/raja7-game-security-guide`, lastModified: new Date("2026-05-30"), changeFrequency: "monthly", priority: 0.7 },
    { url: `${baseUrl}/blog/raja7-game-for-beginners`, lastModified: new Date("2026-05-25"), changeFrequency: "monthly", priority: 0.7 },
    { url: `${baseUrl}/blog/raja7-game-update-whats-new`, lastModified: new Date("2026-05-20"), changeFrequency: "monthly", priority: 0.7 },
    { url: `${baseUrl}/raja7`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.9 },
    { url: `${baseUrl}/raja7-game`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.9 },
    { url: `${baseUrl}/raja7-gaming`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/raja7-apk`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/raja7-game-apk`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/raja7-apk-download`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/raja7-game-download`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.9 },
    { url: `${baseUrl}/raja7-app-download`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/download-raja7`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/raja7-download`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/raja7-game-apk-download`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/raja7-game-install`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/raja7-game-latest-version`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/raja7-game-update`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/raja7-game-free`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/raja7-game-login`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/raja7-login`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/raja7-game-register`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/raja7-register`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/raja7-game-app`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/raja7-game-2026`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/raja7-game-android`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/raja7-game-online`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/raja7-game-play`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/raja7-game-bonus`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/raja7-game-rewards`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/raja7-gamers`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/raja7-game-apk-2026`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/raja7-game-features`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/raja7-game-guide`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/raja7-game-review`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/raja7-game-signup`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/contact`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.5 },
    { url: `${baseUrl}/privacy-policy`, lastModified: new Date(), changeFrequency: "yearly", priority: 0.3 },
    { url: `${baseUrl}/disclaimer`, lastModified: new Date(), changeFrequency: "yearly", priority: 0.3 },
  ];
}
